### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by achevrot** [open-aviation/pitot#15]
Implement performance tests on core functions; if necessary, the following could be a way to optimize it all

- `@default_unit` should also create default `core_*` functions without units for the sake of performance

    ```python
    # in each module, so the decorator should pick the right version
    _core_functions_: dict[str, Callable] = {}

    def __getattr__(funcname: str): 
        if funcname not in _core_functions_:
            raise AttributeError(...)
        return _core_functions_.get(funcname, None)
    ```

**Comment by achevrot** [comment]
poke @junzis

**Comment by junzis** [comment]
sorry, I can't understand the purpose of the code, do you have an example? 😅

**Comment by junzis** [comment]
nevermind, I just saw issue #14. yes. it is clear for me now. Sounds like a great idea 👍
